### ISSUE TITLE
Item Lore Templates

### ISSUE THREAD

**Issue by LJNIC** [Atherys/AtherysRPG#101]
The lore layout for items should be customizable, so that they don't need to be individually configured. A potential config format is described below. Additionally, attributes should have a customizable display (as some attributes may want to use symbols or formatting). Items may also need additional fields, or even configurable fields that can be used as placeholders in the template.

```
item-lore-template=[
  "- $(name) -",
  "",
  "$(attributes)"
]
```

**Comment by cicetil** [comment]
List of placeholders:

**%category%** - Reads from the item's **"category"** config field

**%base-damage%** - Reads from the item's "atherys:base_damage" attribute. 

**%attack-speed%** - Reads the item's attack speed (generic.attack.speed data ?)

**%physical-resistance%** - Reads from the item's "atherys:physical_resistance" attribute.

**%magical-resistance%** - Reads from the item's "atherys:magical_resistance" attribute.

**%attributes%** - Reads all of the attributes on an item. Ignores any attribute(s) on the item which already have placeholders like above. Attributes will be displayed in the order they are listed in the item config. Any attribute(s) added after the item is generated will add them to the next line(s).

**%description%** - Reads from the **"description"** config field.

**%rarity%** - Reads from the item's **"rarity"** config field
```
Item config options
`"category": "(category)",`
```
The item's item category. (Mace, Light Armor, Pickaxe, etc..) Item categories are configurable in a list.
```
item-categories {
"mace" = "&7Mace (Main Hand)"
"light-armor" = "&7Light Armor"
"pickaxe" = "&7Pickaxe"
```
```
"description": [
"&7Lore text which can be read by a placeholder and displayed.",
""
]
```
`"rarity": "(rarity)"`
The item's rarity. Item rarities are configurable in a list.
```
item-rarities {
"common" = "&fCommon"
"uncommon" = "&aUncommon"
"rare" = "&6Rare"
```
