### ISSUE TITLE
Dynamic Class Names

### ISSUE THREAD

**Issue by cicetil** [Atherys/AtherysRPG#99]
Without having actual classes, we can still have the illusion of them with defined class names.
A system to dynamically display a class name based on what skills you have allows players to have a class identity with whatever build they may have.

Example config
```
class-names [

  id="pyromancer"
  display-name="Pyromancer"
  required-skills {
  "fireball",
  "immolate",
  "inferno"
    }
 ]
```
When a player has unlocked all of the required skills, it shows the display name at the top of /skills.
If a player has unlocked all the required skills for multiple classes, it will prioritize the class with the highest amount of required skills.

**Comment by HaedHutner** [comment]
What if a player has unlocked 2 classes?

```hocon
class-names [
  {
    id="pyromancer"
    display-name="Pyromancer"
    required-skills {
      "fireball",
      "immolate",
      "inferno"
    }
  },
  {
    id="firemancer"
    display-name="Firemancer"
    required-skills {
      "fireball",
      "immolate",
      "inferno",
      "skill-4"
    }
  }
]
```

The player has unlocked all of firemancer's skills. Is he a firemancer, or a pyromancer with an extra skill? How would that be determined?

**Comment by LJNIC** [comment]
Whichever class they have the most skills in. If there are two with the same amount, it's random.
